my_name=str("emobilis")
my_number=int(565)
my_number2=float(45.4839)
my_bool=bool(True)
my_bool2=bool(False)
my_complex=complex(1j)

print(my_name)
print(my_number)
print(my_number2)
print(my_bool)
print(my_bool2)
print(my_complex)
